spring:
  jakson:
    default-property-inclusion: non_empty
    serialization.FAIL_ON_EMPTY_BEANS: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: java
    url: jdbc:mysql://localhost:3306/SPRING_SECURITY?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

